// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb22cQJfXyTwxoN_-wlvDyX97JE4eSh_s',
    appId: '1:449510256941:web:327184d5a11be6c8aae3a4',
    messagingSenderId: '449510256941',
    projectId: 'cmsc23-todo-app-lumarquez',
    authDomain: 'cmsc23-todo-app-lumarquez.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-lumarquez.appspot.com',
    measurementId: 'G-K8MRNZYNMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnXwx4c6qwGDwNq1lhMU0MisvzwcrEIBI',
    appId: '1:449510256941:android:fb0880f11f058f47aae3a4',
    messagingSenderId: '449510256941',
    projectId: 'cmsc23-todo-app-lumarquez',
    storageBucket: 'cmsc23-todo-app-lumarquez.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7i_bzyhmGUdFMsleZ_tCi9lecCkKnEFM',
    appId: '1:449510256941:ios:68435008faa5eec1aae3a4',
    messagingSenderId: '449510256941',
    projectId: 'cmsc23-todo-app-lumarquez',
    storageBucket: 'cmsc23-todo-app-lumarquez.appspot.com',
    iosClientId: '449510256941-poq26vhf1i4asgi0phgaeg64grh1283i.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7i_bzyhmGUdFMsleZ_tCi9lecCkKnEFM',
    appId: '1:449510256941:ios:68435008faa5eec1aae3a4',
    messagingSenderId: '449510256941',
    projectId: 'cmsc23-todo-app-lumarquez',
    storageBucket: 'cmsc23-todo-app-lumarquez.appspot.com',
    iosClientId: '449510256941-poq26vhf1i4asgi0phgaeg64grh1283i.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
